# Generated by Django 4.0 on 2024-06-08 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_date_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 8, 22, 18, 33, 694704)),
        ),
    ]
