# Generated by Django 4.0 on 2024-06-08 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_date_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 9, 0, 3, 53, 515240)),
        ),
    ]
